# -*- coding: utf-8 -*-
"""calcolo eta

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FdPyDUH_o31UAx2hzQ1Q2wyfj2TWwxQM
"""

#Calcolo dell'età futura
N=input("inserisci il tuo nome: ")
E=int(input("inserisci la tua eta: "))
EF=E+10
print(f"Mi chiamo {N}, ho {E} anni e tra dieci anni avrò {EF} anni.")